language: android
jdk: oraclejdk8
android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-android-m2repository

script:
  - git clone https://github.com/thewca/tnoodle.git ~/tnoodle && cd ~/tnoodle
  - git checkout v0.15.0
  - ./gradlew publishToMavenLocal
  - "cd -"
  - ./gradlew check
  - "./gradlew :tnoodle-android:assemble"
  - "./gradlew :tnoodlejs-compiler:compileGwt"